### ISSUE TITLE
Usul tambah fitur: Pembuatan APBDes

### ISSUE THREAD

**Issue by telo99** [OpenSID/OpenSID#576]
Seperti sideka: http://panduan.sideka.id/sidekadesktop.html#pengelolaan-apbdes

**Comment by metalab25** [comment]
Sepertinya issue ini mustahil untuk diterapkan karna ini sudah berkali" dibahas cuma bung @eddieridwan tidak mau menerapkan bahkan lebih memilih mengembangkan aplikasi baru seperti OpenSDK

**Comment by MUHAMMADRANGSEL** [comment]
Lebih baik buat menu Apbdes di menu dinamis dan tggl.buat artikel baru copy paste isi apbdes dr aplikasi siskuedes

**Comment by MUHAMMADRANGSEL** [comment]
Lebih gampang dan tdk dua kali kerja bisa hasil export ke pdf atau excel yg dimasukkqn ke aplikasi OpenSID

**Comment by Jehamahdan** [comment]
Ini apa ya... Siskeudes kah?
https://gist.github.com/siayi/3cd22eee14398b8ec673a18515945ce0

**Comment by siayi** [comment]
@Jehamahdan ya ,, itu data SQL (database) pada aplikasi Siskeudes yang kami gunakan di Kabupaten Bandung

**Comment by MUHAMMADRANGSEL** [comment]
Berarti beda dgn kami dilombok timur masih pakai database access

Pada tanggal 15 Sep 2017 11:32, "Ayi Sumarna" <notifications@github.com>
menulis:

@Jehamahdan <https://github.com/jehamahdan> ya ,, itu data SQL (database)
pada aplikasi Siskeudes yang kami gunakan di Kabupaten Bandung

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/eddieridwan/OpenSID/issues/576#issuecomment-329670816>,
or mute the thread

**Comment by siayi** [comment]
Pak @MUHAMMADRANGSEL sebenarnya ga berbeda sih,, di sini juga menggunakan database access. Namun yang ditanyakan oleh @Jehamahdan itu memang data SQL (database) pada aplikasi Siskeudes yang kami gunakan di Kabupaten Bandung, hasil konversi dari database acces (mde) ke SQL

**Comment by mizwaruddin** [comment]
@afa28 sdh ada impor siskeudes. Kalau utk proses pengerjaannya lebih baik langsung dikerjakan di aplikasi siskeudes.
